# app/models/job_profile.py
from backend.app import db

class JobProfile(db.Model):
    __tablename__ = 'job_profiles_review_v3'
    id = db.Column(db.Integer, primary_key=True)
    job_profile = db.Column(db.Text)
    job_code = db.Column(db.BigInteger)
    job_category = db.Column(db.Text)
    job_profile_name = db.Column(db.Text)
    vertical = db.Column(db.Text)
    division = db.Column(db.Text)
    subdivision = db.Column(db.Text)
    primary_reviewer = db.Column(db.Text)
    hr_reviewer = db.Column(db.Text)
    hiring_manager = db.Column(db.Text)
    recruiter_reviewer = db.Column(db.Text)
    position_purpose = db.Column(db.Text)
    key_responsibilities = db.Column(db.Text)
    direct_manager_direct_reports = db.Column(db.Text)
    travel_requirements = db.Column(db.Text)
    physical_requirements = db.Column(db.Text)
    working_conditions = db.Column(db.Text)
    minimum_qualifications = db.Column(db.Text)
    preferred_qualifications = db.Column(db.Text)
    minimum_education = db.Column(db.Text)
    preferred_education = db.Column(db.Text)
    minimum_years_of_work_experience = db.Column(db.Text)
    certifications = db.Column(db.Text)
    competencies = db.Column(db.Text)
    what_you_will_do = db.Column(db.Text)
    what_we_look_for = db.Column(db.Text)
    qualities_that_stir_our_souls = db.Column(db.Text)
    saved_position_purpose = db.Column(db.Text)
    saved_key_responsibilities = db.Column(db.Text)
    saved_direct_manager_direct_reports = db.Column(db.Text)
    saved_travel_requirements = db.Column(db.Text)
    saved_physical_requirements = db.Column(db.Text)
    saved_working_conditions = db.Column(db.Text)
    saved_minimum_qualifications = db.Column(db.Text)
    saved_preferred_qualifications = db.Column(db.Text)
    saved_minimum_education = db.Column(db.Text)
    saved_preferred_education = db.Column(db.Text)
    saved_minimum_years_of_work_experience = db.Column(db.Text)
    saved_certifications = db.Column(db.Text)
    saved_competencies = db.Column(db.Text)
    saved_what_you_will_do = db.Column(db.Text)
    saved_what_we_look_for = db.Column(db.Text)
    saved_qualities_that_stir_our_souls = db.Column(db.Text)
    approved_internal = db.Column(db.Text)
    approved_external = db.Column(db.Text)
    approved_internal_time = db.Column(db.DateTime)
    approved_external_time = db.Column(db.DateTime)

